affinity: {}
fullnameOverride: ""
healthCheckHeaders: {}
image:
  pullPolicy: IfNotPresent
  repository: ngardinerau/pdns-dnsdist:arm64-1.9.4.12
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 53
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []
