{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dnsdist.serviceAccountName" . }}
  labels:
{{ include "dnsdist.labels" . | nindent 4 }}
{{- end -}}
