apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: surrealdb
  template:
    metadata:
      labels:
        app: surrealdb
    spec:
      containers:
        - name: surrealdb
          image: "{{ .Values.image.surrealdb.repository }}:{{ .Values.image.surrealdb.tag }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: surreal-data
              mountPath: /mydata
          command: ["start", "--user", "root", "--pass", "root", "rocksdb:/mydata/mydatabase.db"]
          securityContext:
            runAsUser: 0
      volumes:
        - name: surreal-data
          persistentVolumeClaim:
            claimName: surreal-data-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-notebook
  template:
    metadata:
      labels:
        app: open-notebook
    spec:
      containers:
        - name: open-notebook
          image: "{{ .Values.image.open_notebook.repository }}:{{ .Values.image.open_notebook.tag }}"
          ports:
            - containerPort: 8502
          env:
            - name: OPENAI_API_KEY
              value: "{{ .Values.environment.open_notebook.OPENAI_API_KEY }}"
            - name: SURREAL_ADDRESS
              value: "{{ .Values.environment.open_notebook.SURREAL_ADDRESS }}"
            - name: SURREAL_PORT
              value: "{{ .Values.environment.open_notebook.SURREAL_PORT }}"
            - name: SURREAL_USER
              value: "{{ .Values.environment.open_notebook.SURREAL_USER }}"
            - name: SURREAL_PASS
              value: "{{ .Values.environment.open_notebook.SURREAL_PASS }}"
            - name: SURREAL_NAMESPACE
              value: "{{ .Values.environment.open_notebook.SURREAL_NAMESPACE }}"
            - name: SURREAL_DATABASE
              value: "{{ .Values.environment.open_notebook.SURREAL_DATABASE }}"
          volumeMounts:
            - name: notebook-data
              mountPath: /app/data
      volumes:
        - name: notebook-data
          persistentVolumeClaim:
            claimName: notebook-data-pvc