apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surreal-data-pvc
  labels:
    app: surrealdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.surreal_data.size }}
  storageClassName: {{ .Values.persistence.surreal_data.storageClass }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data-pvc
  labels:
    app: open-notebook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.notebook_data.size }}
  storageClassName: {{ .Values.persistence.notebook_data.storageClass }}